### ISSUE TITLE
Undefined function or variable 'teg_rec_combinations'.

### ISSUE THREAD

**Issue by yzw0041** [thomasgladwin/teg_RMA#1]
Hi,
when I try to use this awesome toolbox, I got the error below. 

Undefined function or variable 'teg_rec_combinations'.

Any idea where this function ?

Thanks 

Yun

**Comment by thomasgladwin** [comment]
Hi Yun,

Thank you for the comment! Sorry for the late reply. The problem was that I changed some file names for clarity:

rec_combo.m is now teg_values_per_cell.m
rec_comb.m is now  teg_rec_combinations.m

The files in the latest upload should all correctly call the renamed functions now. Please let me know if you're still getting an error!

Best,

Thomas

**Comment by thomasgladwin** [comment]
Hi Yun,

Thanks for the comment and sorry for the late reply! Could it be the case that the subdirectory teg_basic_funcs isn't added to the path? You need both teg_basic_funcs and the teg_RMA in the path.

I'll add that to the readme :)

(I also just uploaded an update that handles non-within-subject analyses better, so I'd suggest using the newest files!)

Best,

Thomas
